name: Run Tests with Docker Compose

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.9
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and start services
      run: |
        docker-compose -f lizetest/docker-compose.yml --env-file lizetest/.env up -d --build

    - name: Wait for services to start
      run: sleep 10s 

    # - name: Set up Python
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: '3.11'
    # - name: Wait for server to start
    #   run: |
    #     while ! nc -z localhost 8000; do sleep 1; done
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r lizetest/requirements.txt

    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps

    - name: Run tests
      run: pytest --tracing=retain-on-failure

    - name: Stop and remove services
      run: docker-compose down

