name: Run Tests with Docker Compose

on:
  push:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.9
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and start services
      run: |
        docker-compose -f lizetest/docker-compose.yml --env-file lizetest/.env up -d --build

    - name: Run tests
      run: docker exec lize_server pytest --tracing=retain-on-failure

    - name: Stop and remove services
      run: docker-compose  -f lizetest/docker-compose.yml down

